title = "Simon Bisson"
baseURL = "https://sbisson.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 8 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Simon Bisson"
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-light-blue"
  recent_posts_number = 3

[[params.ananke_socials]]
  name = "bluesky"

  url = "https://bsky.app/profile/sbisson.com"
  label = "@sbisson.com"
[[params.ananke_socials]]
  name = "mastodon"
  rel = "me"
  url = "https://mastodon.social/@sbisson"
  label = "@sbisson"
[[params.ananke_socials]]
  name = "instagram"
  url = "https://www.instagram.com/sbisson/"
  label = "@sbisson"
[[params.ananke_socials]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/sbisson/"
  label = "Simon Bisson"
[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/shbisson"
  label = "@shbisson"
[[params.ananke_socials]]
  name = "facebook"
  url = "https://www.facebook.com/sbisson/"
  label = "Simon Bisson"
[[params.ananke_socials]]
  name = "youtube"
  url = "https://www.youtube.com/@sbisson"
  label = "@sbisson"